// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shdlczoodmekrydnwqsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoZGxjem9vZG1la3J5ZG53cXNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNzk3NzQsImV4cCI6MjA2NDg1NTc3NH0.RTqTGNLgeEahOOzP6wixGq6iQFTeOpDQrjOngXLmdOA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);